GET http://localhost:8080/admin/milestones/histories?page=0&size=3

###
GET http://localhost:8080/milestones/histories/members/202055558?page=0&size=10&sort_by=ACTIVATED_AT&sort_direction=DESC


###
GET http://localhost:8080/milestones/histories/scores/members/202055558?start_date=2024-06-05&end_date=2024-06-08

###
GET http://localhost:8080/admin/milestones/histories/scores?start_date=2024-06-05&end_date=2024-06-10

###

POST http://localhost:8080/milestones/histories
Content-Type: application/json

{
  "milestoneId": 1,
  "description": "대회수상",
  "count": 3,
  "activatedAt": "2024-06-03"
}

###

DELETE http://localhost:8080/milestones/histories/1

###
PATCH http://localhost:8080/admin/milestones/histories/1/approve

###
PATCH http://localhost:8080/admin/milestones/histories/2/reject
Content-Type: application/json

{
  "reason": "증빙자료 불충분"
}
