spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sw_css
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

data:
  client-url: http://localhost:3000
  file-path-prefix: /backend/src/main/resources/static/files
  file-storage-path: /절대 경로/
