insert into college (name) values ('인문대학');
insert into college (name) values ('사회과학대학');
insert into college (name) values ('자연과학대학');
insert into college (name) values ('공과대학');
insert into college (name) values ('사범대학');
insert into college (name) values ('경제통상대학');
insert into college (name) values ('경영대학');
insert into college (name) values ('약학대학');
insert into college (name) values ('생활과학대학');
insert into college (name) values ('예술대학');
insert into college (name) values ('나노과학기술대학');
insert into college (name) values ('생명자원과학대학');
insert into college (name) values ('간호대학');
insert into college (name) values ('의과대학');
insert into college (name) values ('정보의생명공학대학');

insert into major (college_id, name) values (1, '국어국문학과');
insert into major (college_id, name) values (1, '일어일문학과');
insert into major (college_id, name) values (1, '불어불문학과');
insert into major (college_id, name) values (1, '노어노문학과');
insert into major (college_id, name) values (1, '중어중문학과');
insert into major (college_id, name) values (1, '영어영문학과');
insert into major (college_id, name) values (1, '독어독문학과');
insert into major (college_id, name) values (1, '한문학과');
insert into major (college_id, name) values (1, '언어정보학과');
insert into major (college_id, name) values (1, '사학과');
insert into major (college_id, name) values (1, '철학과');
insert into major (college_id, name) values (1, '고고학과');
insert into major (college_id, name) values (2, '행정학과');
insert into major (college_id, name) values (2, '정치외교학과');
insert into major (college_id, name) values (2, '사회복지학과');
insert into major (college_id, name) values (2, '사회학과');
insert into major (college_id, name) values (2, '심리학과');
insert into major (college_id, name) values (2, '문헌정보학과');
insert into major (college_id, name) values (2, '미디어커뮤니케이션학과');
insert into major (college_id, name) values (3, '수학과');
insert into major (college_id, name) values (3, '통계학과');
insert into major (college_id, name) values (3, '물리학과');
insert into major (college_id, name) values (3, '화학과');
insert into major (college_id, name) values (3, '생명과학과');
insert into major (college_id, name) values (3, '미생물학과');
insert into major (college_id, name) values (3, '분자생물학과');
insert into major (college_id, name) values (3, '지질환경과학과');
insert into major (college_id, name) values (3, '대기환경과학과');
insert into major (college_id, name) values (3, '해양학과');
insert into major (college_id, name) values (4, '기계공학부');
insert into major (college_id, name) values (4, '고분자공학과');
insert into major (college_id, name) values (4, '유기소재시스템공학과');
insert into major (college_id, name) values (4, '화공생명·환경공학부 - 화공생명공학전공');
insert into major (college_id, name) values (4, '화공생명·환경공학부 - 환경공학전공');
insert into major (college_id, name) values (4, '전기전자공학부 - 전자공학전공');
insert into major (college_id, name) values (4, '전기전자공학부 - 전기공학전공');
insert into major (college_id, name) values (4, '전기전자공학부 - 반도체공학전공');
insert into major (college_id, name) values (4, '조선해양공학과');
insert into major (college_id, name) values (4, '재료공학부');
insert into major (college_id, name) values (4, '산업공학과');
insert into major (college_id, name) values (4, '항공우주공학과');
insert into major (college_id, name) values (4, '건축공학과');
insert into major (college_id, name) values (4, '건축학과');
insert into major (college_id, name) values (4, '도시공학과');
insert into major (college_id, name) values (4, '사회기반시스템공학과');
insert into major (college_id, name) values (5, '국어교육과');
insert into major (college_id, name) values (5, '영어교육과');
insert into major (college_id, name) values (5, '독어교육과');
insert into major (college_id, name) values (5, '불어교육과');
insert into major (college_id, name) values (5, '교육학과');
insert into major (college_id, name) values (5, '유아교육과');
insert into major (college_id, name) values (5, '특수교육과');
insert into major (college_id, name) values (5, '일반사회교육과');
insert into major (college_id, name) values (5, '역사교육과');
insert into major (college_id, name) values (5, '지리교육과');
insert into major (college_id, name) values (5, '윤리교육과');
insert into major (college_id, name) values (5, '수학교육과');
insert into major (college_id, name) values (5, '물리교육과');
insert into major (college_id, name) values (5, '화학교육과');
insert into major (college_id, name) values (5, '생물교육과');
insert into major (college_id, name) values (5, '지구과학교육과');
insert into major (college_id, name) values (5, '체육교육과');
insert into major (college_id, name) values (6, '무역학부');
insert into major (college_id, name) values (6, '경제학부');
insert into major (college_id, name) values (6, '관광컨벤션학과');
insert into major (college_id, name) values (6, '국제학부');
insert into major (college_id, name) values (6, '공공정책학부');
insert into major (college_id, name) values (7, '경영학과');
insert into major (college_id, name) values (8, '약학대학 - 약학전공');
insert into major (college_id, name) values (8, '약학대학 - 제약학전공');
insert into major (college_id, name) values (9, '아동가족학과');
insert into major (college_id, name) values (9, '의류학과');
insert into major (college_id, name) values (9, '식품영양학과');
insert into major (college_id, name) values (9, '실내환경디자인학과');
insert into major (college_id, name) values (9, '스포츠과학과');
insert into major (college_id, name) values (10, '음악학과');
insert into major (college_id, name) values (10, '한국음악학과');
insert into major (college_id, name) values (10, '미술학과');
insert into major (college_id, name) values (10, '조형학과');
insert into major (college_id, name) values (10, '디자인학과');
insert into major (college_id, name) values (10, '무용학과');
insert into major (college_id, name) values (10, '예술문화영상학과');
insert into major (college_id, name) values (11, '나노메카트로닉스공학과');
insert into major (college_id, name) values (11, '나노에너지공학과');
insert into major (college_id, name) values (11, '광메카트로닉스공학과');
insert into major (college_id, name) values (12, '식물생명과학과');
insert into major (college_id, name) values (12, '원예생명과학과');
insert into major (college_id, name) values (12, '동물생명자원과학과');
insert into major (college_id, name) values (12, '식품공학과');
insert into major (college_id, name) values (12, '생명환경화학과');
insert into major (college_id, name) values (12, '바이오소재과학과');
insert into major (college_id, name) values (12, '바이오산업기계공학과');
insert into major (college_id, name) values (12, '조경학과');
insert into major (college_id, name) values (12, '식품자원경제학과');
insert into major (college_id, name) values (12, 'IT응용공학과');
insert into major (college_id, name) values (12, '바이오환경에너지학과');
insert into major (college_id, name) values (13, '간호학과');
insert into major (college_id, name) values (14, '의예과');
insert into major (college_id, name) values (14, '의학과');
insert into major (college_id, name) values (15, '정보컴퓨터공학부');
insert into major (college_id, name) values (15, '정보컴퓨터공학부 - 컴퓨터공학전공');
insert into major (college_id, name) values (15, '정보컴퓨터공학부 - 인공지능전공');
insert into major (college_id, name) values (15, '의생명융합공학부');

