name: back build test

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  back_build_test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Build with Gradle Wrapper
        run: |
          cd backend
          ./gradlew build
