name: back build test

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  back_build_test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Shutdown the Default MySQL
        run: sudo service mysql stop

      - name: Set up MySQL 8.0
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql version: "8.0"
          mysql database: "sw_css"
          mysql user: root
          mysql password: ${{ secrets.DB_PASSWORD }}
          mysql root password: ${{ secrets.DB_PASSWORD }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - name: Build with Gradle Wrapper
        run: |
          cd backend
          ./gradlew build
