name: front-build-test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd frontend
          npm i

      - name: Create .env File
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: |
          touch .env && \
          jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$SECRETS" | grep $PREFIX > .env

      - name: Build
        run: npm run build
